[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools",
    "setuptools-scm"
]

[project]
name="markdown-render"
version="1.0"
dependencies = [
    "markdown",
    "weasyprint",
]

[project.scripts]
mdr = "mdr.main:main"

